name: Propose to Clean

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  propose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout agent repo
        uses: actions/checkout@v4

      - name: Build filtered payload for Clean
        run: |
          rm -rf clean && mkdir clean
          # Requires a .github/clean-filter.rules file in this repo
          rsync -av --delete --filter='merge .github/clean-filter.rules' . ./clean

      - name: Prepare stable bot branch (one per agent)
        id: prep
        run: echo "branch=bot/${{ github.event.repository.name }}" >> "$GITHUB_OUTPUT"

      - name: Push branch to Clean
        working-directory:
